config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :retail do
      collection do
        get :import_customers
        get :import_orders
        get :export_all_orders
        get :export_all_customers
        get :clear_all_orders_cache
        get :clear_all_customers_cache
        post :retail_update_order
        post :retail_update_user
        # get :states_connection
        post :update_states
      end
    end
  end

  resources :products do
    collection do
      get :icml_catalog
    end
  end

  post '/retail/retail_update_order' => 'retail_callback#retail_update_order'
  post '/retail/retail_update_user' => 'retail_callback#retail_update_user'

end

app/controllers/spree/admin/retail_controller.rb
module Spree
  module Admin
    class RetailController < Spree::Admin::BaseController
      helper 'spree/admin/navigation'

      def index
        @retail_states = RETAIL.statuses.response['statuses'].reject{|k, v| !v['active']}.map{|k, v| [v['name'], k]}
        @payment_states = RETAIL.payment_statuses.response['paymentStatuses'].reject{|k, v| !v['active']}.map{|k, v| [v['name'], k]}
        @payment_types = RETAIL.payment_types.response['paymentTypes'].reject{|k, v| !v['active']}.map{|k, v| [v['name'], k]}
        @delivery_types = RETAIL.delivery_types.response['deliveryTypes'].reject{|k, v| !v['active']}.map{|k, v| [v['name'], v['code']]}
        @user = Spree::User.new
      end

      def import_customers
        RetailImport.create_customers
        flash[:notice] = 'Successfully imported'
        redirect_to :back
      end

      def import_orders
        RetailImport.create_orders
        flash[:notice] = 'Successfully imported'
        redirect_to :back
      end

      # def states_connection
      #   @retail_states = RETAIL.statuses.response['statuses'].map{|k, v| [v['name'], k]}
      #   @user = Spree::User.new
      # end

      def update_states
        RetailImport.update_states(params[:state])
        flash[:notice] = 'Successfully updated'
        redirect_to :back
      end

      # def retail_update_order
      #   head :ok
      # end
      #
      # def retail_update_user
      #   head :ok
      # end

      def export_all_orders
        RetailImport.export_all_orders
        flash[:notice] = 'Successfully exported'
        redirect_to :back
      end

      def export_all_customers
        RetailImport.export_all_customers
        flash[:notice] = 'Successfully exported'
        redirect_to :back
      end

      def clear_all_customers_cache
        RetailImport.clear_all_customers_cache
        flash[:notice] = 'Successfully cleared'
        redirect_to :back
      end

      def clear_all_orders_cache
        RetailImport.clear_all_orders_cache
        flash[:notice] = 'Successfully cleared'
        redirect_to :back
      end

    end
  end
end

app/helpers/spree/retail_helper.rb
module Spree
  module RetailHelper

    def order_states_config(state_name)
      Spree::Config[:state_connection]['order'][state_name]
    end

  end
end

app/views/spree/admin/retail/_delivery_connection.html.erb
<%= form_for :state, url: update_states_admin_retail_index_path do |st| %>
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">
            Методы доставки
          </h1>
        </div>
        <div class="panel-body">
          <%= st.fields_for :delivery_method do |p|%>
            <% Spree::ShippingMethod.all.each do |delivery_method| %>
              <div class="form-group">
                <%= p.label delivery_method.id, delivery_method.name %>
                <%= p.select delivery_method.id, options_for_select(@delivery_types, Spree::Config[:delivery_method] && Spree::Config[:delivery_method][delivery_method.id.to_s]), {include_blank: true}, class: 'form-control' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col-md-4" data-hook="buttons">
      <button name="button" type="submit" class="btn btn-primary "><span class="icon icon-save"></span> Изменить</button>
    </div>
  </div>    
<% end %>

app/views/spree/admin/retail/_payment_connection.html.erb
<%= form_for :state, url: update_states_admin_retail_index_path do |st| %>
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">
            Методы оплаты
          </h1>
        </div>
        <div class="panel-body">
          <%= st.fields_for :payment_method do |p|%>
            <% Spree::PaymentMethod.all.each do |payment_method| %>
              <div class="form-group">
                <%= p.label payment_method.id, payment_method.name %>
                <%= p.select payment_method.id, options_for_select(@payment_types, Spree::Config[:payment_method] && Spree::Config[:payment_method][payment_method.id.to_s]), {include_blank: true}, class: 'form-control' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col-md-4" data-hook="buttons">
      <button name="button" type="submit" class="btn btn-primary "><span class="icon icon-save"></span> Изменить</button>
    </div>
  </div>    
<% end %>

app/views/spree/admin/retail/_states_connection.html.erb
<%= form_for :state, url: update_states_admin_retail_index_path do |st| %>
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">
            Статус заказа
          </h1>
        </div>
        <div class="panel-body">
          <%= st.fields_for :order do |s|%>
            <% Spree::Order.sstatuses.each do |status,no| %>
              <div class="form-group">
                <%= s.label status, Spree.t("order_statuses.#{status}") %>
                  <%= s.select status, options_for_select(@retail_states, Spree::Config[:state_connection]['order'] && Spree::Config[:state_connection]['order'][status]), {include_blank: true}, class: 'form-control' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">
            Статус оплаты
          </h1>
        </div>
        <div class="panel-body">
          <%= st.fields_for :payment do |p|%>
            <% Spree::Order::PAYMENT_STATES.each do |order_state| %>
               <div class="form-group">
                  <%= p.label order_state, t("spree.payment_states.#{order_state}") %>
                  <%= p.select order_state, options_for_select(@payment_states, Spree::Config[:state_connection]['payment'] && Spree::Config[:state_connection]['payment'][order_state]), {include_blank: true}, class: 'form-control' %>
               </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col-md-4" data-hook="buttons">
      <button name="button" type="submit" class="btn btn-primary "><span class="icon icon-save"></span> Изменить</button>
    </div>
  </div>
<% end %>

app/views/spree/admin/retail/index.html.erb
<% content_for :page_title do %>
  RetailCRM
<% end %>
<div class="row">
  <div class="col-sm-12" id="content">
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#connection" id="connection-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Статусы</a></li>
      <li role="presentation"><a href="#payment_connection" id="payment-connection-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Оплата</a></li>
      <li role="presentation"><a href="#delivery_connection" id="delivery-connection-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Доставка</a></li>
      <li role="presentation"><a href="#states" role="tab" id="states-tab" data-toggle="tab" aria-controls="profile">Операции</a></li>
    </ul>
    <br/>
    <div id="myTabContent" class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="connection" aria-labelledby="home-tab">
        <%= render 'states_connection' %>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="payment_connection" aria-labelledby="home-tab">
        <%= render 'payment_connection' %>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="delivery_connection" aria-labelledby="home-tab">
        <%= render 'delivery_connection' %>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="states" aria-labelledby="profile-tab">
        <div class="list-group">
          <%#= link_to 'Импорт клиентов', import_customers_admin_retail_index_path, class: 'list-group-item list-group-item-success' %>
          <%#= link_to 'Импорт заказов', import_orders_admin_retail_index_path, class: 'list-group-item list-group-item-success' %>
          <%= link_to 'Экспорт заказов', export_all_orders_admin_retail_index_path, class: 'list-group-item list-group-item-info' %>
          <%= link_to 'Экспорт клиентов', export_all_customers_admin_retail_index_path, class: 'list-group-item list-group-item-info' %>
          <%= link_to 'Очистить кеш заказов', clear_all_orders_cache_admin_retail_index_path, class: 'list-group-item list-group-item-warning' %>
          <%= link_to 'Очистить кеш клиентов', clear_all_customers_cache_admin_retail_index_path, class: 'list-group-item list-group-item-warning' %>
        </div>
      </div>
    </div>
</div>